# db-properties.yaml
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/jira
    username: jira
    password: JiraRush

  init:
    mode: always

  liquibase:
    changeLog: "classpath:db/changelog.sql"
    contexts: prod
    enabled: true

  data:
    sql: "classpath:data4dev/data.sql"